# Generated by Django 4.2.2 on 2023-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bachelor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('course', models.IntegerField()),
                ('specialization', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
            ],
        ),
    ]
