# Generated by Django 4.2.2 on 2023-07-24 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bachelor',
            table='bachelor',
        ),
    ]
